#!/usr/bin/env php
<?php

date_default_timezone_set('Asia/Jakarta');

include_once(__DIR__.'/vendor/autoload.php');

$command = new \GitBfs\Controller;
$exitCode = $command->execute();
$exitCode = (int) $exitCode;
exit($exitCode);
